Exercise 1
davepmb/DevOps-Course-Starter pull request #1
Opened 2020-08-19 15:23 UTC by davepmb

2020-08-19 16:07 UTC, davepmb commented
I hope I pulled the correct Directory!
I have two on my computer and not sure why I have been having issues with Pulling in Git.

2020-09-04 07:28 UTC, Jonesey13 requested changes
There's still some work to be done here:
1. Goal: Display the list of saved todo items
1. Goal: Create new todo items

We can't approve the PR until these goals have been met.

It may be worth a chat to go over these (we can talk about this during today's call).

2020-09-04 07:28 UTC, Jonesey13 commented on templates/index.html
> +        Pick up Groceries
This is a hardcoded list and not the list of saved todo items from `session_items.py`

2020-09-04 07:28 UTC, Jonesey13 commented on app.py
> +    add_item(title)
These 2 lines are never executed

2020-09-04 07:28 UTC, Jonesey13 commented on app.py
> +    return render_template('index.html')
No data is passed to the template

2020-09-04 14:48 UTC, merged